/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as PracticeAreasRouteImport } from './routes/practice-areas'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as CareerCareerIdRouteImport } from './routes/career.$careerId'
import { Route as NewsNewsIdRouteImport } from './routes/news_.$newsId'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as TeamMemberIdRouteImport } from './routes/team.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasRoute = PracticeAreasRouteImport.update({
  id: '/practice-areas',
  path: '/practice-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCareerIdRoute = CareerCareerIdRouteImport.update({
  id: '/career/$careerId',
  path: '/career/$careerId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news_/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMemberIdRoute = TeamMemberIdRouteImport.update({
  id: '/team/$memberId',
  path: '/team/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/news': typeof NewsRoute
  '/our-team': typeof OurTeamRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/career/$careerId': typeof CareerCareerIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/team/$memberId': typeof TeamMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/news': typeof NewsRoute
  '/our-team': typeof OurTeamRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/career/$careerId': typeof CareerCareerIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/team/$memberId': typeof TeamMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact-us': typeof ContactUsRoute
  '/news': typeof NewsRoute
  '/our-team': typeof OurTeamRoute
  '/practice-areas': typeof PracticeAreasRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/career/$careerId': typeof CareerCareerIdRoute
  '/news_/$newsId': typeof NewsNewsIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/team/$memberId': typeof TeamMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/careers'
    | '/contact-us'
    | '/news'
    | '/our-team'
    | '/practice-areas'
    | '/admin/appointments'
    | '/career/$careerId'
    | '/news/$newsId'
    | '/services/$serviceId'
    | '/team/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/careers'
    | '/contact-us'
    | '/news'
    | '/our-team'
    | '/practice-areas'
    | '/admin/appointments'
    | '/career/$careerId'
    | '/news/$newsId'
    | '/services/$serviceId'
    | '/team/$memberId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/careers'
    | '/contact-us'
    | '/news'
    | '/our-team'
    | '/practice-areas'
    | '/admin/appointments'
    | '/career/$careerId'
    | '/news_/$newsId'
    | '/services/$serviceId'
    | '/team/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CareersRoute: typeof CareersRoute
  ContactUsRoute: typeof ContactUsRoute
  NewsRoute: typeof NewsRoute
  OurTeamRoute: typeof OurTeamRoute
  PracticeAreasRoute: typeof PracticeAreasRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  CareerCareerIdRoute: typeof CareerCareerIdRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  TeamMemberIdRoute: typeof TeamMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas': {
      id: '/practice-areas'
      path: '/practice-areas'
      fullPath: '/practice-areas'
      preLoaderRoute: typeof PracticeAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/$careerId': {
      id: '/career/$careerId'
      path: '/career/$careerId'
      fullPath: '/career/$careerId'
      preLoaderRoute: typeof CareerCareerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$newsId': {
      id: '/news_/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$memberId': {
      id: '/team/$memberId'
      path: '/team/$memberId'
      fullPath: '/team/$memberId'
      preLoaderRoute: typeof TeamMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  CareersRoute: CareersRoute,
  ContactUsRoute: ContactUsRoute,
  NewsRoute: NewsRoute,
  OurTeamRoute: OurTeamRoute,
  PracticeAreasRoute: PracticeAreasRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  CareerCareerIdRoute: CareerCareerIdRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  TeamMemberIdRoute: TeamMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
